BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "casa-avatar"
BBFILE_PATTERN_casa-avatar = "^${LAYERDIR}/"
BBFILE_PRIORITY_casa-avatar = "8"

LAYERDEPENDS_casa-avatar = "core openembedded-layer meta-python raspberrypi"
LAYERSERIES_COMPAT_casa-avatar = "scarthgap"
