<?php
session_start();
if (empty($_SESSION['auth_user'])) { header('Location: /casa/login.php'); exit; }
require_once __DIR__ . '/api/db.php';
$pdo = get_db_pdo();

if (empty($_SESSION['csrf_automation'])) $_SESSION['csrf_automation'] = bin2hex(random_bytes(24));
$csrf = $_SESSION['csrf_automation'];
$message=''; $error='';

function h($v){ return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); }
function slugify_auto($s){ $s=strtolower(trim((string)$s)); $a=iconv('UTF-8','ASCII//TRANSLIT',$s); if($a!==false)$s=$a; $s=preg_replace('/[^a-z0-9\-]+/','-',$s); return trim($s,'-'); }
function json_arr($text){ $v=json_decode((string)$text,true); if(!is_array($v)) throw new RuntimeException('JSON inválido.'); return $v; }

if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (!hash_equals($csrf,$_POST['csrf']??'')) $error='Sessão inválida. Atualize a página.';
    else try {
        $action=$_POST['action']??'';
        if ($action==='scene_save') {
            $id=(int)($_POST['id']??0); $name=trim($_POST['name']??''); if($name==='')throw new RuntimeException('Informe o nome da cena.');
            $slug=slugify_auto($_POST['slug']??$name); $desc=trim($_POST['description']??''); $risk=max(0,min(4,(int)($_POST['risk_level']??1))); $active=isset($_POST['active'])?1:0; $stop=isset($_POST['stop_on_error'])?1:0;
            if($id>0){$pdo->prepare('UPDATE scenes SET slug=:s,nome=:n,descricao=:d,ativo=:a,stop_on_error=:e,risk_level=:r WHERE id=:id')->execute([':s'=>$slug,':n'=>$name,':d'=>$desc,':a'=>$active,':e'=>$stop,':r'=>$risk,':id'=>$id]);}
            else{$pdo->prepare('INSERT INTO scenes(slug,nome,descricao,ativo,stop_on_error,risk_level) VALUES(:s,:n,:d,:a,:e,:r)')->execute([':s'=>$slug,':n'=>$name,':d'=>$desc,':a'=>$active,':e'=>$stop,':r'=>$risk]);$id=(int)$pdo->lastInsertId();}
            $actions=json_arr($_POST['actions_json']??'[]');
            $pdo->beginTransaction();
            $pdo->prepare('DELETE FROM scene_actions WHERE scene_id=:id')->execute([':id'=>$id]);
            $ins=$pdo->prepare('INSERT INTO scene_actions(scene_id,ordem,device_id,comando,payload,prioridade,required_capability,risk_level,ttl_seconds,enabled) VALUES(:s,:o,:d,:c,:p,:pr,:cap,:r,:ttl,:en)');
            $order=10; foreach($actions as $a){ if(!is_array($a))continue; $dev=trim((string)($a['device_id']??''));$cmd=trim((string)($a['command']??$a['comando']??''));if($dev===''||$cmd==='')continue;$pr=strtolower((string)($a['priority']??'normal'));if(!in_array($pr,['low','normal','high','critical'],true))$pr='normal';$ins->execute([':s'=>$id,':o'=>(int)($a['order']??$order),':d'=>$dev,':c'=>substr($cmd,0,120),':p'=>json_encode(is_array($a['payload']??null)?$a['payload']:[],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':pr'=>$pr,':cap'=>trim((string)($a['required_capability']??''))?:null,':r'=>max(0,min(4,(int)($a['risk_level']??1))),':ttl'=>max(10,min(86400,(int)($a['ttl_seconds']??300))),':en'=>(int)($a['enabled']??1)]);$order+=10; }
            $pdo->commit(); $message='Cena salva.';
        } elseif ($action==='scene_toggle') {
            $id=(int)$_POST['id']; $pdo->prepare('UPDATE scenes SET ativo=IF(ativo=1,0,1) WHERE id=:id')->execute([':id'=>$id]); $message='Cena atualizada.';
        } elseif ($action==='rule_save') {
            $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');if($name==='')throw new RuntimeException('Informe o nome da regra.');$slug=slugify_auto($_POST['slug']??$name);$type=$_POST['trigger_type']??'event';if(!in_array($type,['event','state','schedule'],true))$type='event';
            $trigger=json_arr($_POST['trigger_json']??'{}');$conditions=json_arr($_POST['conditions_json']??'[]');$actions=json_arr($_POST['actions_json']??'[]');$enabled=isset($_POST['enabled'])?1:0;$cool=max(0,min(86400,(int)($_POST['cooldown_seconds']??0)));$desc=trim($_POST['description']??'');
            if($id>0){$pdo->prepare('UPDATE automation_rules SET slug=:s,nome=:n,descricao=:d,enabled=:e,trigger_type=:t,trigger_config=:tc,conditions_json=:c,cooldown_seconds=:cd WHERE id=:id')->execute([':s'=>$slug,':n'=>$name,':d'=>$desc,':e'=>$enabled,':t'=>$type,':tc'=>json_encode($trigger,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':c'=>json_encode($conditions,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':cd'=>$cool,':id'=>$id]);}
            else{$pdo->prepare('INSERT INTO automation_rules(slug,nome,descricao,enabled,trigger_type,trigger_config,conditions_json,cooldown_seconds) VALUES(:s,:n,:d,:e,:t,:tc,:c,:cd)')->execute([':s'=>$slug,':n'=>$name,':d'=>$desc,':e'=>$enabled,':t'=>$type,':tc'=>json_encode($trigger,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':c'=>json_encode($conditions,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':cd'=>$cool]);$id=(int)$pdo->lastInsertId();}
            $pdo->beginTransaction();$pdo->prepare('DELETE FROM automation_rule_actions WHERE rule_id=:id')->execute([':id'=>$id]);$ins=$pdo->prepare('INSERT INTO automation_rule_actions(rule_id,ordem,device_id,comando,payload,prioridade,required_capability,risk_level,ttl_seconds,enabled) VALUES(:r,:o,:d,:c,:p,:pr,:cap,:risk,:ttl,:en)');$order=10;foreach($actions as $a){if(!is_array($a))continue;$dev=trim((string)($a['device_id']??''));$cmd=trim((string)($a['command']??$a['comando']??''));if($dev===''||$cmd==='')continue;$pr=strtolower((string)($a['priority']??'normal'));if(!in_array($pr,['low','normal','high','critical'],true))$pr='normal';$ins->execute([':r'=>$id,':o'=>(int)($a['order']??$order),':d'=>$dev,':c'=>substr($cmd,0,120),':p'=>json_encode(is_array($a['payload']??null)?$a['payload']:[],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),':pr'=>$pr,':cap'=>trim((string)($a['required_capability']??''))?:null,':risk'=>max(0,min(4,(int)($a['risk_level']??1))),':ttl'=>max(10,min(86400,(int)($a['ttl_seconds']??300))),':en'=>(int)($a['enabled']??1)]);$order+=10;}$pdo->commit();$message='Regra salva.';
        } elseif ($action==='rule_toggle') {
            $id=(int)$_POST['id'];$pdo->prepare('UPDATE automation_rules SET enabled=IF(enabled=1,0,1) WHERE id=:id')->execute([':id'=>$id]);$message='Regra atualizada.';
        }
    } catch(Throwable $e){ if($pdo->inTransaction())$pdo->rollBack(); $error=$e->getMessage(); }
}

$scenes=$pdo->query("SELECT s.*,COUNT(a.id) actions_total FROM scenes s LEFT JOIN scene_actions a ON a.scene_id=s.id AND a.enabled=1 GROUP BY s.id ORDER BY s.nome")->fetchAll(PDO::FETCH_ASSOC);
$rules=$pdo->query("SELECT r.*,COUNT(a.id) actions_total FROM automation_rules r LEFT JOIN automation_rule_actions a ON a.rule_id=r.id AND a.enabled=1 GROUP BY r.id ORDER BY r.nome")->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CASA — Automação</title><link rel="stylesheet" href="/casa/lcars.css?v=20260917"><style>
body{background:#fff7e8;color:#211b22;font-family:Arial,sans-serif;margin:0}.wrap{max-width:1200px;margin:auto;padding:18px}.head{display:flex;gap:12px}.elbow{background:#f59c73;border-radius:28px 0 0 28px;padding:22px;min-width:150px;font-weight:900}.title{background:#d8b4ea;flex:1;padding:18px 24px;border-radius:0 24px 24px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:14px;margin-top:16px}.card{background:#fff;border:3px solid #d8b4ea;border-radius:20px;padding:16px}.orange{border-color:#f59c73}.blue{border-color:#8eb9ee}.green{border-color:#8ccf9c}input,textarea,select,button{font:inherit;padding:9px;border-radius:9px;border:1px solid #777;box-sizing:border-box}input,textarea,select{width:100%}textarea{font-family:monospace}button{background:#f59c73;font-weight:800;cursor:pointer}.row{display:flex;gap:8px;align-items:center}.row>*{flex:1}.pill{display:inline-block;padding:5px 10px;border-radius:999px;font-weight:800}.on{background:#9bd6a4}.off{background:#ef9b92}.msg{padding:10px;border-radius:10px;background:#dff3df;margin-top:12px}.err{background:#ffd9d3}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}.top a{display:inline-block;padding:10px 14px;background:#8eb9ee;border-radius:12px;color:#211b22;text-decoration:none;font-weight:800;margin-right:6px}</style></head><body><div class="wrap">
<div class="head"><div class="elbow">CASA<br>AUTO</div><div class="title"><h1>Cenas e Regras</h1><div>Automação determinística do JARVIS</div></div></div>
<div class="top" style="margin-top:12px"><a href="/casa/index.php">Dashboard</a><a href="/casa/dispositivos_pessoais.php">Dispositivos</a></div>
<?php if($message):?><div class="msg"><?=h($message)?></div><?php endif;?><?php if($error):?><div class="msg err"><?=h($error)?></div><?php endif;?>
<div class="grid"><div class="card orange"><h2>Nova cena</h2><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="scene_save"><label>Nome<input name="name" required></label><label>Slug<input name="slug"></label><label>Descrição<textarea name="description" rows="2"></textarea></label><div class="row"><label>Risco<select name="risk_level"><?php for($i=0;$i<=4;$i++):?><option><?=$i?></option><?php endfor;?></select></label><label><input type="checkbox" name="active" checked> Ativa</label><label><input type="checkbox" name="stop_on_error"> Parar no erro</label></div><label>Ações JSON<textarea name="actions_json" rows="10">[
  {"device_id":"luz_sala","command":"power_on","payload":{},"risk_level":1}
]</textarea></label><button>Salvar cena</button></form></div>
<div class="card blue"><h2>Nova regra</h2><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="rule_save"><label>Nome<input name="name" required></label><label>Slug<input name="slug"></label><label>Tipo<select name="trigger_type"><option value="event">Evento</option><option value="state">Estado</option><option value="schedule">Horário</option></select></label><label>Trigger JSON<textarea name="trigger_json" rows="4">{"event_type":"sensor.presence","device_id":"sensor_corredor"}</textarea></label><label>Condições JSON<textarea name="conditions_json" rows="4">[{"field":"data.presence","op":"eq","value":true}]</textarea></label><label>Ações JSON<textarea name="actions_json" rows="5">[{"device_id":"luz_corredor","command":"power_on","risk_level":1}]</textarea></label><div class="row"><label>Cooldown<input type="number" name="cooldown_seconds" value="30" min="0"></label><label><input type="checkbox" name="enabled" checked> Ativa</label></div><button>Salvar regra</button></form></div></div>
<div class="card green" style="margin-top:16px"><h2>Cenas cadastradas</h2><table><tr><th>Nome</th><th>Risco</th><th>Ações</th><th>Estado</th><th></th></tr><?php foreach($scenes as $s):?><tr><td><?=h($s['nome'])?><br><small><?=h($s['slug'])?></small></td><td><?=h($s['risk_level'])?></td><td><?=h($s['actions_total'])?></td><td><span class="pill <?=$s['ativo']?'on':'off'?>"><?=$s['ativo']?'ATIVA':'DESATIVADA'?></span></td><td><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="scene_toggle"><input type="hidden" name="id" value="<?=h($s['id'])?>"><button>Alternar</button></form></td></tr><?php endforeach;?></table></div>
<div class="card blue" style="margin-top:16px"><h2>Regras cadastradas</h2><table><tr><th>Nome</th><th>Tipo</th><th>Ações</th><th>Último disparo</th><th>Estado</th><th></th></tr><?php foreach($rules as $r):?><tr><td><?=h($r['nome'])?><br><small><?=h($r['slug'])?></small></td><td><?=h($r['trigger_type'])?></td><td><?=h($r['actions_total'])?></td><td><?=h($r['last_triggered_at']?:'—')?></td><td><span class="pill <?=$r['enabled']?'on':'off'?>"><?=$r['enabled']?'ATIVA':'DESATIVADA'?></span></td><td><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="rule_toggle"><input type="hidden" name="id" value="<?=h($r['id'])?>"><button>Alternar</button></form></td></tr><?php endforeach;?></table></div>
</div></body></html>
