<?php
session_start();
if (empty($_SESSION['auth_user'])) { header('Location: /casa/login.php'); exit; }
require_once __DIR__ . '/api/db.php';
$pdo=get_db_pdo();
if(empty($_SESSION['csrf_iot'])) $_SESSION['csrf_iot']=bin2hex(random_bytes(24));
$csrf=$_SESSION['csrf_iot']; $message=''; $error='';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function caps($v){$a=json_decode((string)$v,true);return is_array($a)?$a:[];}
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,$_POST['csrf']??'')) $error='Sessão inválida. Atualize a página.';
  else try{
    if(($_POST['action']??'')==='relay_state'){
      $deviceId=trim((string)($_POST['device_id']??'')); $on=($_POST['relay_on']??'0')==='1';
      $st=$pdo->prepare("SELECT device_id,capabilities FROM dispositivos_cluster WHERE device_id=:d LIMIT 1");$st->execute([':d'=>$deviceId]);$dev=$st->fetch(PDO::FETCH_ASSOC);
      if(!$dev) throw new RuntimeException('Dispositivo não encontrado.');
      $c=caps($dev['capabilities']??'[]'); if(!in_array('relay',$c,true)&&!in_array('switch',$c,true)) throw new RuntimeException('Este dispositivo não anuncia capacidade de relé.');
      $json=json_encode(['relay_on'=>$on],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
      $pdo->prepare("INSERT INTO device_desired_state(device_id,desired_state,updated_at) VALUES(:d,:s,NOW()) ON DUPLICATE KEY UPDATE desired_state=VALUES(desired_state),updated_at=NOW()")->execute([':d'=>$deviceId,':s'=>$json]);
      $message='Estado desejado atualizado para '.($on?'LIGADO':'DESLIGADO').'. O ESP aplicará na próxima consulta.';
    }
  }catch(Throwable $e){$error=$e->getMessage();}
}
$devices=[];$env=[];
try{$devices=$pdo->query("SELECT d.device_id,d.nome,d.model,d.status,d.ultimo_heartbeat,d.capabilities,d.metadata,s.desired_state,s.updated_at desired_updated FROM dispositivos_cluster d LEFT JOIN device_desired_state s ON s.device_id=d.device_id ORDER BY d.nome,d.device_id")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}
try{$env=$pdo->query("SELECT r.device_id,r.temperature_c,r.humidity_pct,r.sensor_type,r.observed_at FROM device_environment_readings r INNER JOIN (SELECT device_id,MAX(id) id FROM device_environment_readings GROUP BY device_id) x ON x.id=r.id ORDER BY r.device_id")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}
$envBy=[];foreach($env as $r)$envBy[$r['device_id']]=$r;
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CASA — Dispositivos IoT</title><link rel="stylesheet" href="/casa/lcars.css?v=20260914b"><style>body{background:#fff7e8;color:#211b22;font-family:Arial,sans-serif;margin:0}.wrap{max-width:1180px;margin:auto;padding:18px}.head{display:flex}.elbow{background:#f59c73;border-radius:28px 0 0 28px;min-width:140px;padding:24px;font-weight:900}.title{background:#d8b4ea;flex:1;padding:18px 24px;border-radius:0 24px 24px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:14px;margin-top:16px}.card{background:#fff;border:3px solid #8eb9ee;border-radius:20px;padding:16px}.relay{border-color:#f59c73}.sensor{border-color:#8ccf9c}.pill{display:inline-block;padding:5px 10px;border-radius:999px;font-weight:800}.ok{background:#9bd6a4}.off{background:#ef9b92}.msg{padding:10px;border-radius:10px;margin-top:12px;background:#dff3df}.err{background:#ffd9d3}button,a.btn{font:inherit;padding:10px 14px;border:0;border-radius:12px;background:#f59c73;color:#211b22;font-weight:800;text-decoration:none;cursor:pointer}.values{display:flex;gap:10px}.value{flex:1;background:#f5f5f5;border-radius:14px;padding:14px;text-align:center}.big{font-size:2rem;font-weight:900}.history{max-height:230px;overflow:auto}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><div class="wrap"><div class="head"><div class="elbow">CASA<br>IOT</div><div class="title"><h1>Relés + Ambiente</h1><div>Estado desejado e histórico de temperatura/umidade</div></div></div><p><a class="btn" href="/casa/index.php">Dashboard</a></p><?php if($message):?><div class="msg"><?=h($message)?></div><?php endif;?><?php if($error):?><div class="msg err"><?=h($error)?></div><?php endif;?><div class="grid">
<?php foreach($devices as $d): $c=caps($d['capabilities']??'[]');$isRelay=in_array('relay',$c,true)||in_array('switch',$c,true);$r=$envBy[$d['device_id']]??null;$isSensor=$r||in_array('temperature',$c,true)||in_array('humidity',$c,true);if(!$isRelay&&!$isSensor)continue; $desired=json_decode((string)($d['desired_state']??''),true);$want=is_array($desired)&&array_key_exists('relay_on',$desired)?(bool)$desired['relay_on']:false;$meta=json_decode((string)($d['metadata']??''),true);$actual=is_array($meta)&&array_key_exists('relay_on',$meta)?(bool)$meta['relay_on']:null;?>
<?php if($isRelay):?><div class="card relay"><h2><?=h($d['nome']?:$d['model']?:$d['device_id'])?></h2><p><span class="pill <?=($d['status']==='online')?'ok':'off'?>"><?=h(strtoupper($d['status']?:'offline'))?></span></p><p>Desejado: <b><?=$want?'LIGADO':'DESLIGADO'?></b> · Físico: <b><?=$actual===null?'--':($actual?'LIGADO':'DESLIGADO')?></b></p><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="relay_state"><input type="hidden" name="device_id" value="<?=h($d['device_id'])?>"><button name="relay_on" value="1">Ligar</button> <button name="relay_on" value="0">Desligar</button></form><small>Último heartbeat: <?=h($d['ultimo_heartbeat']?:'--')?> · Estado definido: <?=h($d['desired_updated']?:'--')?></small></div><?php endif;?>
<?php if($isSensor):?><div class="card sensor"><h2><?=h($d['nome']?:$d['model']?:$d['device_id'])?></h2><?php if($r):?><div class="values"><div class="value"><div class="big"><?=h($r['temperature_c'])?> °C</div>Temperatura</div><div class="value"><div class="big"><?=h($r['humidity_pct'])?>%</div>Umidade</div></div><p>Última mudança: <?=h($r['observed_at'])?></p><div class="history"><table><tr><th>Data</th><th>°C</th><th>%</th></tr><?php $st=$pdo->prepare("SELECT observed_at,temperature_c,humidity_pct FROM device_environment_readings WHERE device_id=:d ORDER BY id DESC LIMIT 50");$st->execute([':d'=>$d['device_id']]);foreach($st as $x):?><tr><td><?=h($x['observed_at'])?></td><td><?=h($x['temperature_c'])?></td><td><?=h($x['humidity_pct'])?></td></tr><?php endforeach;?></table></div><?php else:?><p>Aguardando primeira leitura ambiental.</p><?php endif;?></div><?php endif;?>
<?php endforeach;?></div></div></body></html>