#Criado por Marcelo Maurin MArtins
#Criado por:Marcelo Maurin Martins
#Data:09/08/2013

CC=gcc
CFLAGS=-W -Wall -ansi  -pedantic 
EXEC=Comlink
OBJ=Comlink.o
FONTE=Comlink.c

all: compile 
	@echo "Compilando programa"

compile:
	$(CC) $(CFLAGS) -o $(EXEC) $(FONTE)

install:
	cp ./$(EXEC) /usr/local/bin/$(EXEC)




