#!/bin/sh

set -e


# Source debconf library
. /usr/share/debconf/confmodule
db_get casasite/localhost
localhost = "$RET"

db_get casasite/username
username = "$RET"

db_get casasite/password
password = "$RET"


echo "Parametros de instalacao"
echo "localhost: $localhost"
echo "username: $username"
echo "password: $password"


#DEBHELPER#

exit 0
